### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by skcajs**
Update readme for easier reading, more verbose instructions.

### CODE REVIEW

**Comment by hgeorgsch** [comment]
There is a typo in this line
```
Find your gcc version, and make sure it's included in the . This is needed for below
```
I am not quite sure what is intended.

Have you done something to add instructions inside the prebuild packages?  I didn't but you have added the claim ...

This line seems to come to late in the sequence:
```
cd {/path/to/CosmoSim/root/dir}
```
Either needed before `conan install` or it goes without saying.

I really hate instructions to use a particular editor.  Why on Earth would I want to use something as awkward as nano?  Never mind.  Nobody else will take offence.

You have a very long section on customising conan?  Is this absolutely necessary?  Lengthy instructions tend to put me off as a user, but since I do not know conan properly, I do not know why you have included it all.

**Comment by skcajs** [comment]
I can change to "editor of your choice" ;) I use both and don't have a preference.

I'm using a very clean Linux environment that I've just reinstalled... so I've opted to include any additional commands I needed to do to make the instructions work as intended. Quite a bit of the installing Conan process was scouring the internet for solutions. I think removal of any of the additional steps would result in a broken build process, especially for someone like me who isn't that familiar with C++.

That said, possibly the gcc check is overkill. But again, cecking the settings.yml for the version was just something I needed to do to get "cmake . -B build" to run properly.

If you'd prefer, these steps could be in a section called "troubleshooting"? 

I'll fix the typo.

**Comment by skcajs** [comment]
though having said that... the issues maybe ubuntu specific...

**Comment by hgeorgsch** [comment]
I never needed that much fiddling with conan, and I have never elsewhere used either conan nor C++.
If in doubt, I would suggest to move conan setup to a separate page and link it, keeping just a bare minimum in README.

There is a workflow to do the release, it triggers when you push a 'v*' tag.  There should be a release branch for every minor version.  Patch versions should be new tags on the appropriate minor version branch. New releases should be merged into master, except when they are patches to old minor releases.

You should not merge this into master before you have made a release, but you may merge it into develop.

**Pull request closed without merging**
